---
- name: check if ansible is not to old
  hosts: localhost
  tags:
   - default
  roles:
    - version
  gather_facts: no

- name: install packages, ntp and setup dotfiles
  hosts: all
  tags:
    - packages
  roles:
    - base_packages
    - ranger
    - ntp
    - dotfiles
    - bat

- name: install and configure bbb
  hosts: bbb
  tags:
    - bbb
    - bigbluebutton
  roles:
    - bigbluebutton
