---
- name: check if ansible is not to old
  hosts: localhost
  tags:
   - default
  roles:
    - version
  gather_facts: no

- name: install packages, ntp and setup dotfiles
  hosts: all
  tags:
    - packages
  roles:
    - base_packages
    - ranger
    - ntp
    - dotfiles
    - bat

- name: add more ssh keys (ugly)
  hosts: all
  tags: ssh
  tasks:
    - name: Set authorized keys taken from url
      authorized_key:
        user: root
        state: present
        key: "{{ item }}"
      with_items:
        - https://github.com/do1jlr.keys

- name: install and configure bbb
  hosts: bbb
  tags:
    - bbb
    - bigbluebutton
  roles:
#    - bigbluebutton
    - bbb_mail_fixed
