---
- name: check if ansible is not to old
  hosts: localhost
  tags:
   - default
  roles:
    - version
  gather_facts: no

- name: install packages, ntp and setup dotfiles
  hosts: all
  tags:
    - packages
  roles:
    - base_packages
    - ranger
    - ntp
    - dotfiles
    - bat

- name: add more ssh keys (ugly)
  hosts: all
  tags: ssh
  tasks:
    - name: Set authorized keys taken from url
      authorized_key:
        user: root
        state: present
        key: "{{ item }}"
      with_items:
        - https://github.com/do1jlr.keys
        - https://github.com/0boro.keys
        - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNjEfNBpZPB8ATdY2bQtBYjXss4GEzIF2FV7Cx9RMYC waschtl"

    - name: set correkt fqdn
      hostname:
        name: "{{ bbb_hostname }}"

- name: install and configure bbb
  hosts: bbb
  tags:
    - default
    - bbb
    - bigbluebutton
  roles:
    - bigbluebutton

- name: try install scalelite without docker
  hosts: scalelite
  roles:
    - scalelite
  tags:
    - default
    - scalelite

- name: try install scalelite with docker
  hosts: docker
  roles:
    - docker-scalelite
  tags:
    - docker
    - docker-scalelite

- name: try to install greenlight
  hosts: greenlight
  tags:
    - default
    - greenlight
  roles:
    - greenlight

- name: install node-exporter
  hosts: all
  tags: node-exporter
  roles:
    - node-exporter
